name: "PR-Labeler"
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  label: 
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
